# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUERyPPzst7Z4UXX4xByMQCnFSNqVpso
"""

import pandas as pd

df = pd.read_csv('credit_risk_dataset.csv.zip')
print(f'O dataset possui {df.shape[0]} linhas e {df.shape[1]} colunas.\n')
df.info()
df.isnull().sum()

df.head()

# 1. Preenchendo nulos do tempo de emprego com a mediana
mediana_emprego = df['person_emp_length'].median()
df['person_emp_length'] = df['person_emp_length'].fillna(mediana_emprego)

# 2. Preenchendo nulos da taxa de juros com a média
media_juros = df['loan_int_rate'].mean()
df['loan_int_rate'] = df['loan_int_rate'].fillna(media_juros)


print("Valores nulos após o tratamento:")
print(df.isnull().sum())

# 1. Ver quantas pessoas têm tempo de emprego maior que 60 anos
print("Quantidade de linhas com tempo de emprego ilógico:")
print(df[df['person_emp_length'] > 60].shape[0])

# 2. Ver o exemplo de algumas dessas linhas para entender a idade delas
df[df['person_emp_length'] > 60][['person_age', 'person_emp_length']]
df.shape[0]

# Mantém no DataFrame apenas as linhas onde o tempo de emprego é menor ou igual a 60
df = df[df['person_emp_length'] <= 60]

# Confirma o novo tamanho do dataset (deve ter 2 linhas a menos)
print(f"Novo tamanho do dataset: {df.shape[0]} linhas.")

df.to_csv('credit_risk_limpo.csv', index = False)

